<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cb_newscal"
 *
 * Auto generated by Extension Builder 2014-12-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Calendar for news',
	'description' => 'Display news as calendar of the month.',
	'author' => 'Charles Brunet',
	'author_email' => 'charles@cbrunet.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'news' => '3.0.0-3.0.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);